const products = [
    {
        id: "001",
        type: "newyear",
        status: "Còn hàng",
        image: "../assets/images/products/product-001.jpg",
        name: "Thiệp Tết - 18 x 12 cm",
        occasion: "Tết",
        price: "10.100",
    },
    {
        id: "002",
        type: "newyear",
        status: "Còn hàng",
        image: "../assets/images/products/product-002.jpg",
        name: "Thiệp Tết - 18 x 12 cm",
        occasion: "Tết",
        price: "10.100",
    },
    {
        id: "003",
        type: "valentine",
        status: "Còn hàng",
        image: "../assets/images/products/product-003.jpg",
        name: "Thiệp Valentine - 15 x 10.5 cm",
        occasion: "Valentine",
        price: "20.500",
    },
    {
        id: "004",
        type: "aniversary",
        status: "Còn hàng",
        image: "../assets/images/products/product-004.jpg",
        name: "Thiệp Chúc Mừng LUX - Blueangel",
        occasion: "Chúc mừng",
        price: "7.500",
    },
    {
        id: "005",
        type: "newyear",
        status: "Còn hàng",
        image: "../assets/images/products/product-005.jpg",
        name: "Thiệp Tết - 18 x 12 cm",
        occasion: "Tết",
        price: "15.100",
    },
    {
        id: "006",
        type: "newyear",
        status: "Còn hàng",
        image: "../assets/images/products/product-006.jpg",
        name: "Thiệp Chúc Mừng Ngày Nhà Giáo Việt Nam 20.11 - 15 x 11 cm",
        occasion: "Tết",
        price: "9.900",
    },
    {
        id: "007",
        type: "womanday",
        status: "Còn hàng",
        image: "../assets/images/products/product-007.jpg",
        name: "Thiệp Chúc Mừng Ngày Phụ Nữ Việt Nam - 20.10",
        occasion: "Ngày Phụ Nữ Việt Nam",
        price: "5.500",
    },
    {
        id: "008",
        type: "teacherday",
        status: "Còn hàng",
        image: "../assets/images/products/product-008.jpg",
        name: "Thiệp Chúc Mừng Ngày Nhà Giáo Việt Nam 20.11 ",
        occasion: "Ngày Nhà Giáo Việt Nam",
        price: "8.600",
    },
    {
        id: "009",
        type: "birthday",
        status: "Còn hàng",
        image: "../assets/images/products/product-009.jpg",
        name: "Thiệp Happy Birthday",
        occasion: "Sinh Nhật",
        price: "11.200",
    },
    {
        id: "010",
        type: "valentine",
        status: "Còn hàng",
        image: "../assets/images/products/product-010.jpg",
        name: "Thiệp Valentine - 15 x 10.5 cm",
        occasion: "Tết",
        price: "9.500",
    },
    {
        id: "011",
        type: "teacherday",
        status: "Còn hàng",
        image: "../assets/images/products/product-011.jpg",
        name: "Thiệp Chúc Mừng Ngày Nhà Giáo Việt Nam 20.11",
        occasion: "Ngày Nhà Giáo Việt Nam",
        price: "8.800",
    },
    {
        id: "012",
        type: "newyear",
        status: "Còn hàng",
        image: "../assets/images/products/product-012.jpg",
        name: "Thiệp Quilling Tết 16 x 16 cm",
        occasion: "Tết",
        price: "10.100",
    },
    {
        id: "013",
        type: "newyear",
        status: "Còn hàng",
        image: "../assets/images/products/product-013.jpg",
        name: "Thiệp Tết - 18 x 12 cm",
        occasion: "Tết",
        price: "15.100",
    },
    {
        id: "014",
        type: "valentine",
        status: "Còn hàng",
        image: "../assets/images/products/product-014.jpg",
        name: "Thiệp I Love You - 10.5 x 7.5 cm",
        occasion: "Valentine",
        price: "6.100",
    },
    {
        id: "015",
        type: "teacherday",
        status: "Còn hàng",
        image: "../assets/images/products/product-015.jpg",
        name: "Thiệp Chúc Mừng Ngày Nhà Giáo Việt Nam 20.11",
        occasion: "Tết",
        price: "8.600",
    },
];

export { products };
